version: '3.8'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0 # ✅ versi stabil non-KRaft
    container_name: kafka
    ports:
        - "9092:9092"
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,PLAINTEXT_INTERNAL://kafka:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  spark:
    image: bitnami/spark:3.3.0
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./datasets:/datasets
      - ./spark-apps:/opt/spark-apps
      - ./data-lake:/opt/data-lake
      - ./jars:/opt/spark-apps/jars
    depends_on:
      - kafka

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
    volumes:
      - ./superset:/app/superset_home
